repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: stable
  hooks:
    - id: black
      language_version: python3.7
- repo: https://github.com/kynan/nbstripout
  rev: master
  hooks:
    - id: nbstripout
      files: ".ipynb"
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.8
  hooks:
    - id: flake8
      types: [file, python]
      args: ['--ignore=E401,W503', '--max-line-length=120']
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.780
  hooks:
    - id: mypy
      args: [--ignore-missing-imports, --disallow-untyped-defs]
      files: notebooks/
    - id: mypy
      args: [--ignore-missing-imports, --disallow-untyped-defs]
      files: covid_impact
