name: mdlz_covid
channels:
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.3
  - arviz=0.9.0
  - attrs=19.3.0
  - backcall=0.2.0
  - black=19.10b0
  - bleach=3.1.5
  - bzip2=1.0.8
  - ca-certificates=2020.6.20
  - cctools=927.0.2
  - certifi=2020.6.20
  - cfgv=3.1.0
  - cftime=1.2.0
  - clang=9.0.1
  - clang-tools=9.0.1
  - clang_osx-64=9.0.1
  - clangxx=9.0.1
  - clangxx_osx-64=9.0.1
  - click=7.1.2
  - compiler-rt=9.0.1
  - compiler-rt_osx-64=9.0.1
  - convertdate=2.2.1
  - coverage=5.2
  - curl=7.71.1
  - cycler=0.10.0
  - cython=0.29.21
  - dbus=1.13.6
  - decorator=4.4.2
  - defusedxml=0.6.0
  - distlib=0.3.1
  - editdistance=0.5.3
  - entrypoints=0.3
  - ephem=3.7.7.1
  - expat=2.2.9
  - fbprophet=0.6
  - filelock=3.0.12
  - flake8=3.8.3
  - freetype=2.10.2
  - gettext=0.19.8.1
  - glib=2.65.0
  - hdf4=4.2.13
  - hdf5=1.10.6
  - holidays=0.10.2
  - icu=64.2
  - identify=1.4.23
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - ipykernel=5.3.2
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.1
  - jinja2=2.11.2
  - joblib=0.16.0
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.5
  - jupyter_console=6.1.0
  - jupyter_contrib_core=0.3.3
  - jupyter_contrib_nbextensions=0.5.1
  - jupyter_core=4.6.3
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.4
  - jupyter_nbextensions_configurator=0.4.1
  - kiwisolver=1.2.0
  - korean_lunar_calendar=0.2.1
  - krb5=1.17.1
  - ld64=450.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libcurl=7.71.1
  - libcxx=10.0.0
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libiconv=1.15
  - liblapack=3.8.0
  - libllvm9=9.0.1
  - libnetcdf=4.7.4
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libpq=12.2
  - libsodium=1.0.17
  - libssh2=1.9.0
  - libxml2=2.9.10
  - libxslt=1.1.33
  - llvm-openmp=10.0.0
  - lunarcalendar=0.0.9
  - lxml=4.5.2
  - markupsafe=1.1.1
  - matplotlib-base=3.2.2
  - mccabe=0.6.1
  - mistune=0.8.4
  - more-itertools=8.4.0
  - mypy=0.782
  - mypy_extensions=0.4.3
  - nbconvert=5.6.1
  - nbformat=5.0.7
  - nbstripout=0.3.9
  - ncurses=6.1
  - netcdf4=1.5.3
  - nodeenv=1.4.0
  - notebook=6.0.3
  - nspr=4.20
  - nss=3.47
  - numpy=1.18.5
  - openssl=1.1.1g
  - packaging=20.4
  - pandas=1.0.5
  - pandoc=2.10
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pathspec=0.8.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.1.1
  - pluggy=0.13.1
  - pre-commit=2.6.0
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.5
  - prompt_toolkit=3.0.5
  - psutil=5.7.0
  - ptyprocess=0.6.0
  - py=1.9.0
  - pycodestyle=2.6.0
  - pyflakes=2.2.0
  - pygments=2.6.1
  - pymeeus=0.3.7
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyrsistent=0.16.0
  - pystan=2.19.1.1
  - pytest=5.4.3
  - pytest-cov=2.10.0
  - python=3.7.6
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2020.1
  - pyyaml=5.3.1
  - pyzmq=19.0.1
  - qt=5.12.5
  - qtconsole=4.7.5
  - qtpy=1.9.0
  - readline=8.0
  - regex=2020.6.8
  - scikit-learn=0.23.1
  - scipy=1.5.0
  - send2trash=1.5.0
  - setuptools=49.1.2
  - six=1.15.0
  - sqlite=3.32.3
  - tapi=1000.10.8
  - terminado=0.8.3
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toml=0.10.1
  - tornado=6.0.4
  - traitlets=4.3.3
  - typed-ast=1.4.1
  - typing_extensions=3.7.4.2
  - vim=8.2.1149
  - virtualenv=20.0.20
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xarray=0.15.1
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
